# Generated by Django 4.0.6 on 2022-07-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='cumpleaños',
            field=models.CharField(max_length=50),
        ),
    ]
