# Generated by Django 4.0.6 on 2022-07-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_alter_familiar_cumpleaños'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='cumpleaños',
            new_name='cumpleanos',
        ),
    ]
